version: '3.8'

services:
  web:
    build: .
    ports:
      - "8888:8888"
    environment:
      - DB_AS400_USER=${DB_AS400_USER}
      - DB_AS400_PASS=${DB_AS400_PASS}
      - DB_AS400_HOST=${DB_AS400_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    command: python app.py
