version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_USER}
      - DB_HOST=${DB_HOST}
    command: python app.py
